"""Contains Models (db tables) for storing data related to the video output"""

from django.db import models


class Video(models.Model):
    """
    Model combining video metadata and associated word/sentence data.
    Fields:
        video_id (CharField): Unique identifier for the video generated by YouTube.
        word (CharField): Key word within the associated sentence.
        sentence (CharField): Original sentence in the video's language.
        translated_sentence (CharField): Sentence translated to English.
        title (CharField): Title of the video.
        description (TextField): Description of the video content.
        upload_date (DateTimeField): Date and time of the video upload.
    """
    video_id = models.CharField(max_length=255, unique=True, primary_key=True)
    word = models.CharField(max_length=25, null=True, blank=True)
    sentence = models.CharField(max_length=300, null=True, blank=True)
    translated_sentence = models.CharField(max_length=300, null=True, blank=True)
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    upload_time = models.DateTimeField(null=True, blank=True)
    thumbnail_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.video_id

    class Meta:
        db_table = "videos"

