"""Contains Models (db tables) for storing data related to the video output"""

from django.db import models


class Video(models.Model):
    video_id = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField()
    thumbnail_url = models.URLField()
    upload_date = models.DateTimeField(default="2024-11-05T15:41:31Z")

    def __str__(self):
        return self.video_id


class Sentences(models.Model):
    video_id = models.CharField(max_length=50, unique=True)
    word = models.CharField(max_length=25)
    sentence = models.CharField(max_length=300)
    translated_sentence = models.CharField(max_length=300)


class VideoDetails(models.Model):
    """
    Model combining video metadata and associated word/sentence data.

    Fields:
        video_id (CharField): Unique identifier for the video generated by YouTube.
        word (CharField): Key word within the associated sentence.
        sentence (CharField): Original sentence in the video's language.
        translated_sentence (CharField): Sentence translated to English.
        title (CharField): Title of the video.
        description (TextField): Description of the video content.
        upload_date (DateTimeField): Date and time of the video upload.
    """
    video_id = models.CharField(max_length=50, unique=True)
    word = models.CharField(max_length=25)
    sentence = models.CharField(max_length=300)
    translated_sentence = models.CharField(max_length=300)
    title = models.CharField(max_length=200)
    description = models.TextField()
    upload_date = models.DateTimeField()
    thumbnail_url = models.URLField()
