from rest_framework import serializers

from today.models import Video


class VideoDetailsSerializer(serializers.ModelSerializer):
    """
    Serializer for the VideoDetails model, which handles video metadata and
    associated word/sentence data for use in API responses.

    Fields:
        video_id (str): Unique identifier for the video generated by YouTube.
        word (str): Key word in the associated sentence.
        sentence (str): Original sentence in the video's language.
        translated_sentence (str): Sentence translated to English.
        title (str): Title of the video.
        description (str): Description of the video content.
        upload_date (datetime): Date and time of the video upload.
        thumbnail_url (str): URL of the video's thumbnail image.
    """
    class Meta:
        model = Video
        fields = [
            "video_id",
            "word",
            "sentence",
            "translated_sentence",
            "title",
            "description",
            "upload_time",
            "thumbnail_url",
        ]
